# Site settings
title: Leo
subtitle: Hi,Welcome1
keywords: Leo,  生活记录，分享 
description: leo's space, 暂未开通公众号
baseurl: "" # the subpath of your site, e.g. /blog
url: "luozju.github.io" # 你的网址
domain: "https://julystar.top" # 你的域名
page_no_title: "leo's blog" # 文章无标题时默认显示内容
beian: # "备案号"
author: leo
email: lynet@zju.edu.cn

# Build settings
permalink: /:year/:month/:day/:title/
exclude: ["README.md", "changelog.md", "server", "tools", "Pipfile"]
plugins:
  - jekyll-paginate
  - jemoji

markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM

# Pageinate settings
page_size: 8 # 分页大小
paginate_path: "page:num"

# Search settings
baidu_search: true
google_search: #true

# Menu settings
menu:
  - page: 首页
    directory: .
    icon: icon-home
  - page: 归档
    directory: archives/
    icon: icon-archive
  - page: 关于
    directory: about/
    icon: icon-about
  - page: 标签
    directory: tags/
    icon: icon-tags
  - page: 留言
    directory: guestbook/
    icon: icon-guestbook

# Link settings
links: # 友情链接
  - title: leo's github
    url: https://github.com/luoyuzju


valine:
  enable: true
  app_id: B69wdAqHw2nm2tfFSevNdDU8-gzGzoHsz
  app_key: GsMjFzS4H2wlRSepCg7Uxjms
  notify: false # mail notifier , https://github.com/xCss/Valine/wiki
  verify: false # Verification code
  visitor: true
  avatar: retro
  placeholder: say something~~\n - 昵称 为你所要显示的评论的ID；\n - 邮箱 只有后台可见，仅供讨论过程中是否需要交流邮件而设置，请放心填写;\n - 网址 为你的评论的昵称的超链接。
  guest_info: nick,mail,link
  pageSize: 12